#!/bin/bash
set -euo pipefail

SLIME=${SLIME:-/mnt/shared-storage-gpfs2/wangqianyi2/slime}
cd "$SLIME"

PIPELINE_LOG_DIR=${PIPELINE_LOG_DIR:-$SLIME/logs/pipeline}
PIPELINE_RUN_TS=${PIPELINE_RUN_TS:-$(date +%Y%m%d-%H%M%S)}
PIPELINE_RUN_TAG=${PIPELINE_RUN_TAG:-pipeline_${PIPELINE_RUN_TS}}
RUN_LOG=$PIPELINE_LOG_DIR/${PIPELINE_RUN_TAG}.log
RUN_ENV=$PIPELINE_LOG_DIR/${PIPELINE_RUN_TAG}.env

mkdir -p "$PIPELINE_LOG_DIR"

TRACKED_ENV_KEYS=(
  DATA_MODE
  MODEL_ROOT
  MODEL_SH
  MODEL_NAME_FOR_EXPORT
  BASE_HF_DIR
  BASE_TORCH_DIST_DIR
  SFT_ENABLED
  SFT_HF_DIR
  SFT_MEGATRON_DIR
  SFT_DATA_PATH
  SFT_SYNTH_FULL_DATA_PATH
  NUM_ROUNDS
  NUM_ROLLOUT_PER_ROUND
  BOOTSTRAP_NUM_ROLLOUT
  KEEP_ALL_ROUND_CHECKPOINTS
  KEEP_ALL_ROUND_REWARD_SNAPSHOTS
  KEEP_FINAL_POLICY_PER_ROUND
  KEEP_FINAL_REWARD_PER_ROUND
  REWARD_MODEL_INIT
  REWARD_DIR
  TEST_DATA
  PROMPT_DATA
  DEMO_DATA
  REWARD_TRAIN_DATA_PATH
  REWARD_EXTERNAL_EVAL_PATH
  REWARD_EVAL_REJECTED_KEY_PASS
  EVAL_DIR
  EVAL_WINRATE_DIR
  ROLLOUT_DIR
  TENSORBOARD_ROOT
  ADVANTAGE_ESTIMATOR
  N_SAMPLES_PER_PROMPT
  NORMALIZE_ADVANTAGES
  PPO_START_FROM_SFT
  PPO_REF_FIXED_TO_SFT
  ROLLOUT_TEMPERATURE
  ROLLOUT_MAX_RESPONSE_LEN
  ROLLOUT_HEALTH_MAX_TRUNCATED
  PROMPT_LABEL_KEY_PASS
  SLIME_RUBRIC_ENABLED
  SLIME_RUBRIC_PLUGINS
  SLIME_RUBRIC_W_IRL
  SLIME_RUBRIC_W_FORMAT
  SLIME_RUBRIC_W_ANSWER
  SLIME_WARMUP_RM_ENABLED
  SLIME_WARMUP_RM_DIR
  SLIME_WARMUP_RM_COEF
  ACTOR_LR
  CRITIC_LR
  KL_LOSS_COEF
  TOTAL_GPUS
  ACTOR_NUM_GPUS
  CRITIC_NUM_GPUS
  ROLLOUT_NUM_GPUS
  ROLLOUT_NUM_GPUS_PER_ENGINE
  TENSOR_MODEL_PARALLEL_SIZE
  SGLANG_MEM_FRACTION_STATIC
  REWARD_EVAL_MAX_SAMPLES
  REWARD_EVAL_SHUFFLE_SEED
  REWARD_UPDATE_EPOCHS
  REWARD_UPDATE_BATCH_SIZE
  REWARD_ONLINE_PREF_WEIGHT
  EVAL_TEMPERATURE
  WINRATE_GATE_ENABLED
  WINRATE_GATE_MAX_ROUND
  WINRATE_GATE_MAX_SAMPLES
  WINRATE_GATE_CONCURRENCY
  WINRATE_GATE_MIN
  INTERROUND_WINRATE_GATE_MIN
  START_ROUND
  FROM_SCRATCH
  BT_PRETRAIN_ENABLED
  BT_PRETRAIN_DIR
  BT_PRETRAIN_BASE_MODEL
  REWARD_BT_FULL_DATA_PATH
  REWARD_BT_WARMUP_SAMPLES
  REWARD_BT_WARMUP_SEED
  REWARD_BT_WARMUP_DATA_PATH
  REWARD_BT_EVAL_PATH
  REWARD_BT_EPOCHS
  REWARD_BT_BATCH_SIZE
  REWARD_BT_EVAL_BATCH_SIZE
  REWARD_BT_LR
  REWARD_BT_HOLDOUT_RATIO
  REWARD_BT_EVAL_INTERVAL
  REWARD_BT_C_COEF_INIT
  REWARD_BT_TB_DIR
)

{
cat <<EOF
run_tag=$PIPELINE_RUN_TAG
run_log=$RUN_LOG
cwd=$(pwd)
git_head=$(git rev-parse --short HEAD 2>/dev/null || true)
hostname=$(hostname)
start_time=$(date '+%Y-%m-%d %H:%M:%S %Z')
command=bash scripts/run-full-pipeline-job.sh $*
EOF
for key in "${TRACKED_ENV_KEYS[@]}"; do
  if [ -n "${!key:-}" ]; then
    printf '%s=%s\n' "$key" "${!key}"
  fi
done
} > "$RUN_ENV"

echo "[pipeline-log] writing to $RUN_LOG"
echo "[pipeline-log] env snapshot $RUN_ENV"

{
  echo "[pipeline-log] start $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo "[pipeline-log] command bash scripts/run-full-pipeline-job.sh $*"
  bash scripts/run-full-pipeline-job.sh "$@"
} 2>&1 | tee -a "$RUN_LOG"

exit ${PIPESTATUS[0]}
